create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  name text not null default 'Anonymous',
  rating int not null check (rating between 1 and 5),
  comment text not null,
  created_at timestamptz not null default now()
);

alter table public.ratings enable row level security;

drop policy if exists "Public can read ratings" on public.ratings;
create policy "Public can read ratings"
  on public.ratings
  for select
  using (true);

drop policy if exists "Public can insert ratings" on public.ratings;
create policy "Public can insert ratings"
  on public.ratings
  for insert
  with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'ratings'
  ) then
    alter publication supabase_realtime add table public.ratings;
  end if;
end $$;
